### ISSUE TITLE
Redirect Loop After adding to VIM

### ISSUE THREAD

**Issue by KMCGit** [logicahealth/sandbox-community-edition#11]
I am attempting to set this up, but I am experiencing the mentioned redirect loop at the first screen (localhost:3001). 

I have appended the following to /etc/hosts using sudo:
127.0.0.1  keycloak
127.0.0.1  sandbox-mysql
127.0.0.1  sandbox-manager-api
127.0.0.1  sandbox
127.0.0.1  dstu2
127.0.0.1  stu3
127.0.0.1  r4
127.0.0.1  r5
127.0.0.1  static-content

Here is my full file:
![image](https://github.com/user-attachments/assets/ba96ba12-6fbd-49e1-80ad-d7be6f5c361e)

I have reopened the file to make sure they were present. The webpage loads the Logica screen but continues to reload the screen indefinitely. 

Note: I am attempting this on an M1 Mac, using Rosetta in Docker

**Comment by preston** [comment]
FYI we are going to start pointing people to the Meld fork pretty soon. https://github.com/Interop-community/meld/tree/main/community-contents
