### ISSUE TITLE
Sandbox.logicahealth.org is down

### ISSUE THREAD

**Issue by dfischman1** [logicahealth/sandbox-community-edition#4]
Hi,
I apologize since this is probably not the right point-of-contact, but I wasn't sure where else I could raise the issue. Sandbox.logicahealth.org is not loading. This was verified by 5+ people. Would you be able to look into this?

**Comment by preston** [comment]
@dfischman1 FYI it's back up and operational again. There was an underlying database issue that took down the system for everyone.
