### ISSUE TITLE
mysql error when creating new sandbox

### ISSUE THREAD

**Issue by rlabercrombie** [logicahealth/sandbox-community-edition#7]
When creating a new sandbox, both myself and another dev on the team received the following error in an exception: 
caching_sha2_password.so: cannot open shared object file

There does seem to be a lot of documentation pointing to libraries not having caught up to the sha2 password plugin, especially with mysql 8.  

As a temporary local fix, modifying the compose file to include the bolded 'command' allowed us to finally create a sandbox without the error above occurring.  It does provide a new spam message in the logs related to mysql_native_password being deprecated however.... 

  sandbox-mysql:
    image: logicahealth/sandbox-mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - logica-sandbox-volume:/var/lib/mysql57
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    **command: ['mysqld', '--default-authentication-plugin=mysql_native_password']**
    healthcheck:
      test: ["CMD-SHELL", "/wait-for-db.sh"]
      interval: 10s
      timeout: 60s
      retries: 50

**Comment by preston** [comment]
@rlabercrombie FYI I've applied your suggested change.

**Comment by preston** [comment]
Please remove if issues persist..
